name: PR Notification

on:
  pull_request:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            🚀 New Pull Request Created!
            Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.event.pull_request.user.login }}
            Link: ${{ github.event.pull_request.html_url }}
